[auth]
client_id = "developer-tmo-led-display"
client_secret = "vQmFOck9yHQz4AokHzWkGvApfqdIbCcG"

[options]
rows = 64
cols = 64
chain_length = 2
parallel = 1
brightness = 30
hardware_mapping = 'adafruit-hat-pwm'
show_refresh_rate = true
limit_refresh_rate_hz = 120

[runtime_options]
gpio_slowdown = -1